from . import _typing as typ
from .enums import U2FTransport


class DeviceRegistration():

    version: str = ...
    app_id: str = ...
    key_handle: bytes = ...
    public_key: bytes = ...
    counter: int = ...

    # U2FTransports
    u2f_transports: U2FTransport = ...

    def device_as_client_dict(self) -> typ.Dict[str, typ.Any]:
        ...
